#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, 
# displays Best School and then Hi on a new line.
# Requirements: You must use the while loop

counter=0
while [ $counter -lt 10 ];do
    echo "Best School"
    ((counter++))
    if [ $counter == 9 ];then
       echo "Hi"
    fi
done`
